// This file is @generated by oxidris-cli generate-board-feature-stats.
// To regenerate, run: make regenerate-board-feature-stats

impl crate::board_feature::source::NumHoles {
    pub const P01: f32 = 0.0;
    pub const P05: f32 = 0.0;
    pub const P10: f32 = 0.0;
    pub const P25: f32 = 1.0;
    pub const P50: f32 = 5.0;
    pub const P75: f32 = 14.0;
    pub const P90: f32 = 26.0;
    pub const P95: f32 = 33.0;
    pub const P99: f32 = 63.0;
}

impl crate::board_feature::source::SumOfHoleDepth {
    pub const P01: f32 = 0.0;
    pub const P05: f32 = 0.0;
    pub const P10: f32 = 0.0;
    pub const P25: f32 = 3.0;
    pub const P50: f32 = 19.0;
    pub const P75: f32 = 78.0;
    pub const P90: f32 = 188.0;
    pub const P95: f32 = 260.0;
    pub const P99: f32 = 499.0;
}

impl crate::board_feature::source::MaxHeight {
    pub const P01: f32 = 2.0;
    pub const P05: f32 = 2.0;
    pub const P10: f32 = 3.0;
    pub const P25: f32 = 4.0;
    pub const P50: f32 = 8.0;
    pub const P75: f32 = 13.0;
    pub const P90: f32 = 17.0;
    pub const P95: f32 = 18.0;
    pub const P99: f32 = 20.0;
}

impl crate::board_feature::source::CenterColumnMaxHeight {
    pub const P01: f32 = 1.0;
    pub const P05: f32 = 2.0;
    pub const P10: f32 = 2.0;
    pub const P25: f32 = 4.0;
    pub const P50: f32 = 8.0;
    pub const P75: f32 = 13.0;
    pub const P90: f32 = 16.0;
    pub const P95: f32 = 18.0;
    pub const P99: f32 = 20.0;
}

impl crate::board_feature::source::TotalHeight {
    pub const P01: f32 = 6.0;
    pub const P05: f32 = 12.0;
    pub const P10: f32 = 16.0;
    pub const P25: f32 = 32.0;
    pub const P50: f32 = 65.0;
    pub const P75: f32 = 108.0;
    pub const P90: f32 = 143.0;
    pub const P95: f32 = 159.0;
    pub const P99: f32 = 179.0;
}

impl crate::board_feature::source::SurfaceBumpiness {
    pub const P01: f32 = 2.0;
    pub const P05: f32 = 3.0;
    pub const P10: f32 = 4.0;
    pub const P25: f32 = 6.0;
    pub const P50: f32 = 8.0;
    pub const P75: f32 = 14.0;
    pub const P90: f32 = 25.0;
    pub const P95: f32 = 32.0;
    pub const P99: f32 = 48.0;
}

impl crate::board_feature::source::SurfaceRoughness {
    pub const P01: f32 = 2.0;
    pub const P05: f32 = 4.0;
    pub const P10: f32 = 6.0;
    pub const P25: f32 = 8.0;
    pub const P50: f32 = 12.0;
    pub const P75: f32 = 19.0;
    pub const P90: f32 = 33.0;
    pub const P95: f32 = 45.0;
    pub const P99: f32 = 69.0;
}

impl crate::board_feature::source::RowTransitions {
    pub const P01: f32 = 3.0;
    pub const P05: f32 = 5.0;
    pub const P10: f32 = 7.0;
    pub const P25: f32 = 11.0;
    pub const P50: f32 = 20.0;
    pub const P75: f32 = 35.0;
    pub const P90: f32 = 47.0;
    pub const P95: f32 = 54.0;
    pub const P99: f32 = 67.0;
}

impl crate::board_feature::source::ColumnTransitions {
    pub const P01: f32 = 5.0;
    pub const P05: f32 = 8.0;
    pub const P10: f32 = 9.0;
    pub const P25: f32 = 11.0;
    pub const P50: f32 = 17.0;
    pub const P75: f32 = 30.0;
    pub const P90: f32 = 46.0;
    pub const P95: f32 = 54.0;
    pub const P99: f32 = 64.0;
}

impl crate::board_feature::source::SumOfWellDepth {
    pub const P01: f32 = 0.0;
    pub const P05: f32 = 0.0;
    pub const P10: f32 = 0.0;
    pub const P25: f32 = 0.0;
    pub const P50: f32 = 1.0;
    pub const P75: f32 = 4.0;
    pub const P90: f32 = 10.0;
    pub const P95: f32 = 15.0;
    pub const P99: f32 = 25.0;
}

impl crate::board_feature::source::NumClearedLines {
    pub const P01: f32 = 0.0;
    pub const P05: f32 = 0.0;
    pub const P10: f32 = 0.0;
    pub const P25: f32 = 0.0;
    pub const P50: f32 = 0.0;
    pub const P75: f32 = 0.0;
    pub const P90: f32 = 1.0;
    pub const P95: f32 = 1.0;
    pub const P99: f32 = 2.0;
}

impl crate::board_feature::source::EdgeIWellDepth {
    pub const P01: f32 = 0.0;
    pub const P05: f32 = 0.0;
    pub const P10: f32 = 0.0;
    pub const P25: f32 = 1.0;
    pub const P50: f32 = 2.0;
    pub const P75: f32 = 4.0;
    pub const P90: f32 = 7.0;
    pub const P95: f32 = 10.0;
    pub const P99: f32 = 14.0;
}
