use std::{
    collections::HashSet,
    io::{self, Write as _},
    iter,
    path::PathBuf,
};

use anyhow::Context as _;
use oxidris_evaluator::board_feature::{self, BoxedBoardFeature};

use crate::{
    analysis::{BoardFeatureStatistics, BoardSample},
    model::session::SessionCollection,
    util::{self, Output},
};

#[derive(Default, Debug, Clone, clap::Args)]
pub(crate) struct GenerateBoardFeatureStatsArg {
    /// Boards data file path
    boards_file: PathBuf,
    /// Output file path
    #[arg(long)]
    output: Option<PathBuf>,
}

pub fn run(arg: &GenerateBoardFeatureStatsArg) -> anyhow::Result<()> {
    let GenerateBoardFeatureStatsArg {
        boards_file,
        output,
    } = arg;

    let features = board_feature::all_board_features();

    eprintln!("Loading boards from {}...", boards_file.display());
    let boards = SessionCollection::open(boards_file)?.sessions;
    eprintln!("Loaded {} boards", boards.len());

    eprintln!("Computing featuress for all boards...");
    let board_samples = BoardSample::from_sessions(&features, &boards);
    eprintln!("Features computed");

    eprintln!("Computing statistics");
    let statistics = BoardFeatureStatistics::from_samples(&features, &board_samples);
    eprintln!("Statistics computed");

    let mut writer = Output::from_output_path(output.clone())?;
    dump_source(&mut writer, &features, &statistics).with_context(|| {
        format!(
            "Failed to write source code to {}",
            output
                .as_ref()
                .map_or_else(|| "stdout".to_string(), |p| p.display().to_string())
        )
    })?;
    writer.flush().with_context(|| {
        format!(
            "Failed to write source code to {}",
            output
                .as_ref()
                .map_or_else(|| "stdout".to_string(), |p| p.display().to_string())
        )
    })?;

    Ok(())
}

fn dump_source(
    writer: &mut dyn io::Write,
    features: &[BoxedBoardFeature],
    statistics: &[BoardFeatureStatistics],
) -> anyhow::Result<()> {
    writeln!(
        writer,
        "// This file is @generated by oxidris-cli generate-board-feature-stats."
    )?;
    writeln!(
        writer,
        "// To regenerate, run: make regenerate-board-feature-stats"
    )?;
    let mut generated_types = HashSet::new();
    for (f, stats) in iter::zip(features, statistics) {
        let type_name = f.feature_source().type_name();
        if !generated_types.insert(type_name) {
            continue;
        }
        writeln!(writer)?;
        writeln!(
            writer,
            "impl {} {{",
            type_name.replace("oxidris_evaluator::", "crate::")
        )?;
        for percentile in [1u8, 5, 10, 25, 50, 75, 90, 95, 99] {
            let value = stats.raw.percentiles.get(f32::from(percentile)).unwrap();
            let s = util::format_f32(value);
            writeln!(writer, "    pub const P{percentile:02}: f32 = {s};",)?;
        }
        writeln!(writer, "}}")?;
    }

    Ok(())
}
