// This file is @generated by oxidris-cli generate-board-feature-stats.
// To regenerate, run: make regenerate-board-feature-stats

impl crate::board_feature::HolesPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 1.0;
    pub const RAW_P75: f32 = 4.0;
    pub const RAW_P90: f32 = 7.0;
    pub const RAW_P95: f32 = 10.0;
    pub const RAW_P99: f32 = 20.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 1.0;
    pub const TRANSFORMED_P75: f32 = 4.0;
    pub const TRANSFORMED_P90: f32 = 7.0;
    pub const TRANSFORMED_P95: f32 = 10.0;
    pub const TRANSFORMED_P99: f32 = 20.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.3;
    pub const NORMALIZED_P25: f32 = 0.6;
    pub const NORMALIZED_P50: f32 = 0.9;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::HoleDepthPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 2.0;
    pub const RAW_P75: f32 = 16.0;
    pub const RAW_P90: f32 = 44.0;
    pub const RAW_P95: f32 = 68.0;
    pub const RAW_P99: f32 = 152.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 2.0;
    pub const TRANSFORMED_P75: f32 = 16.0;
    pub const TRANSFORMED_P90: f32 = 44.0;
    pub const TRANSFORMED_P95: f32 = 68.0;
    pub const TRANSFORMED_P99: f32 = 152.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.352_941_16;
    pub const NORMALIZED_P25: f32 = 0.764_705_9;
    pub const NORMALIZED_P50: f32 = 0.970_588_2;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::RowTransitionsPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 3.0;
    pub const RAW_P10: f32 = 4.0;
    pub const RAW_P25: f32 = 6.0;
    pub const RAW_P50: f32 = 10.0;
    pub const RAW_P75: f32 = 19.0;
    pub const RAW_P90: f32 = 30.0;
    pub const RAW_P95: f32 = 38.0;
    pub const RAW_P99: f32 = 53.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 3.0;
    pub const TRANSFORMED_P10: f32 = 4.0;
    pub const TRANSFORMED_P25: f32 = 6.0;
    pub const TRANSFORMED_P50: f32 = 10.0;
    pub const TRANSFORMED_P75: f32 = 19.0;
    pub const TRANSFORMED_P90: f32 = 30.0;
    pub const TRANSFORMED_P95: f32 = 38.0;
    pub const TRANSFORMED_P99: f32 = 53.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.228_571_41;
    pub const NORMALIZED_P25: f32 = 0.542_857_17;
    pub const NORMALIZED_P50: f32 = 0.8;
    pub const NORMALIZED_P75: f32 = 0.914_285_7;
    pub const NORMALIZED_P90: f32 = 0.971_428_6;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::ColumnTransitionsPenalty {
    pub const RAW_P01: f32 = 3.0;
    pub const RAW_P05: f32 = 5.0;
    pub const RAW_P10: f32 = 6.0;
    pub const RAW_P25: f32 = 9.0;
    pub const RAW_P50: f32 = 11.0;
    pub const RAW_P75: f32 = 15.0;
    pub const RAW_P90: f32 = 21.0;
    pub const RAW_P95: f32 = 25.0;
    pub const RAW_P99: f32 = 39.0;
    pub const TRANSFORMED_P01: f32 = 3.0;
    pub const TRANSFORMED_P05: f32 = 5.0;
    pub const TRANSFORMED_P10: f32 = 6.0;
    pub const TRANSFORMED_P25: f32 = 9.0;
    pub const TRANSFORMED_P50: f32 = 11.0;
    pub const TRANSFORMED_P75: f32 = 15.0;
    pub const TRANSFORMED_P90: f32 = 21.0;
    pub const TRANSFORMED_P95: f32 = 25.0;
    pub const TRANSFORMED_P99: f32 = 39.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.199_999_99;
    pub const NORMALIZED_P25: f32 = 0.5;
    pub const NORMALIZED_P50: f32 = 0.7;
    pub const NORMALIZED_P75: f32 = 0.8;
    pub const NORMALIZED_P90: f32 = 0.95;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::SurfaceBumpinessPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 3.0;
    pub const RAW_P10: f32 = 3.0;
    pub const RAW_P25: f32 = 5.0;
    pub const RAW_P50: f32 = 7.0;
    pub const RAW_P75: f32 = 11.0;
    pub const RAW_P90: f32 = 20.0;
    pub const RAW_P95: f32 = 28.0;
    pub const RAW_P99: f32 = 46.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 3.0;
    pub const TRANSFORMED_P10: f32 = 3.0;
    pub const TRANSFORMED_P25: f32 = 5.0;
    pub const TRANSFORMED_P50: f32 = 7.0;
    pub const TRANSFORMED_P75: f32 = 11.0;
    pub const TRANSFORMED_P90: f32 = 20.0;
    pub const TRANSFORMED_P95: f32 = 28.0;
    pub const TRANSFORMED_P99: f32 = 46.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.32;
    pub const NORMALIZED_P25: f32 = 0.68;
    pub const NORMALIZED_P50: f32 = 0.840_000_03;
    pub const NORMALIZED_P75: f32 = 0.92;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::SurfaceRoughnessPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 4.0;
    pub const RAW_P10: f32 = 5.0;
    pub const RAW_P25: f32 = 7.0;
    pub const RAW_P50: f32 = 10.0;
    pub const RAW_P75: f32 = 15.0;
    pub const RAW_P90: f32 = 24.0;
    pub const RAW_P95: f32 = 35.0;
    pub const RAW_P99: f32 = 65.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 4.0;
    pub const TRANSFORMED_P10: f32 = 5.0;
    pub const TRANSFORMED_P25: f32 = 7.0;
    pub const TRANSFORMED_P50: f32 = 10.0;
    pub const TRANSFORMED_P75: f32 = 15.0;
    pub const TRANSFORMED_P90: f32 = 24.0;
    pub const TRANSFORMED_P95: f32 = 35.0;
    pub const TRANSFORMED_P99: f32 = 65.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.354_838_73;
    pub const NORMALIZED_P25: f32 = 0.645_161_3;
    pub const NORMALIZED_P50: f32 = 0.806_451_6;
    pub const NORMALIZED_P75: f32 = 0.903_225_8;
    pub const NORMALIZED_P90: f32 = 0.967_741_97;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::WellDepthPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 0.0;
    pub const RAW_P75: f32 = 3.0;
    pub const RAW_P90: f32 = 8.0;
    pub const RAW_P95: f32 = 14.0;
    pub const RAW_P99: f32 = 25.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 0.0;
    pub const TRANSFORMED_P75: f32 = 3.0;
    pub const TRANSFORMED_P90: f32 = 8.0;
    pub const TRANSFORMED_P95: f32 = 14.0;
    pub const TRANSFORMED_P99: f32 = 25.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.428_571_4;
    pub const NORMALIZED_P25: f32 = 0.785_714_27;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::DeepWellRisk {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 0.0;
    pub const RAW_P75: f32 = 3.0;
    pub const RAW_P90: f32 = 8.0;
    pub const RAW_P95: f32 = 14.0;
    pub const RAW_P99: f32 = 25.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 0.0;
    pub const TRANSFORMED_P75: f32 = 3.0;
    pub const TRANSFORMED_P90: f32 = 8.0;
    pub const TRANSFORMED_P95: f32 = 14.0;
    pub const TRANSFORMED_P99: f32 = 25.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.545_454_5;
    pub const NORMALIZED_P25: f32 = 1.0;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::MaxHeightPenalty {
    pub const RAW_P01: f32 = 1.0;
    pub const RAW_P05: f32 = 2.0;
    pub const RAW_P10: f32 = 2.0;
    pub const RAW_P25: f32 = 3.0;
    pub const RAW_P50: f32 = 4.0;
    pub const RAW_P75: f32 = 8.0;
    pub const RAW_P90: f32 = 13.0;
    pub const RAW_P95: f32 = 16.0;
    pub const RAW_P99: f32 = 19.0;
    pub const TRANSFORMED_P01: f32 = 1.0;
    pub const TRANSFORMED_P05: f32 = 2.0;
    pub const TRANSFORMED_P10: f32 = 2.0;
    pub const TRANSFORMED_P25: f32 = 3.0;
    pub const TRANSFORMED_P50: f32 = 4.0;
    pub const TRANSFORMED_P75: f32 = 8.0;
    pub const TRANSFORMED_P90: f32 = 13.0;
    pub const TRANSFORMED_P95: f32 = 16.0;
    pub const TRANSFORMED_P99: f32 = 19.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.214_285_73;
    pub const NORMALIZED_P25: f32 = 0.571_428_54;
    pub const NORMALIZED_P50: f32 = 0.857_142_87;
    pub const NORMALIZED_P75: f32 = 0.928_571_4;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::CenterColumnsPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 1.0;
    pub const RAW_P10: f32 = 1.0;
    pub const RAW_P25: f32 = 2.0;
    pub const RAW_P50: f32 = 4.0;
    pub const RAW_P75: f32 = 8.0;
    pub const RAW_P90: f32 = 13.0;
    pub const RAW_P95: f32 = 15.0;
    pub const RAW_P99: f32 = 18.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 1.0;
    pub const TRANSFORMED_P10: f32 = 1.0;
    pub const TRANSFORMED_P25: f32 = 2.0;
    pub const TRANSFORMED_P50: f32 = 4.0;
    pub const TRANSFORMED_P75: f32 = 8.0;
    pub const TRANSFORMED_P90: f32 = 13.0;
    pub const TRANSFORMED_P95: f32 = 15.0;
    pub const TRANSFORMED_P99: f32 = 18.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.142_857_13;
    pub const NORMALIZED_P25: f32 = 0.5;
    pub const NORMALIZED_P50: f32 = 0.785_714_27;
    pub const NORMALIZED_P75: f32 = 0.928_571_4;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::CenterTopOutRisk {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 1.0;
    pub const RAW_P10: f32 = 1.0;
    pub const RAW_P25: f32 = 2.0;
    pub const RAW_P50: f32 = 4.0;
    pub const RAW_P75: f32 = 8.0;
    pub const RAW_P90: f32 = 13.0;
    pub const RAW_P95: f32 = 15.0;
    pub const RAW_P99: f32 = 18.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 1.0;
    pub const TRANSFORMED_P10: f32 = 1.0;
    pub const TRANSFORMED_P25: f32 = 2.0;
    pub const TRANSFORMED_P50: f32 = 4.0;
    pub const TRANSFORMED_P75: f32 = 8.0;
    pub const TRANSFORMED_P90: f32 = 13.0;
    pub const TRANSFORMED_P95: f32 = 15.0;
    pub const TRANSFORMED_P99: f32 = 18.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.285_714_27;
    pub const NORMALIZED_P25: f32 = 1.0;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::TopOutRisk {
    pub const RAW_P01: f32 = 1.0;
    pub const RAW_P05: f32 = 2.0;
    pub const RAW_P10: f32 = 2.0;
    pub const RAW_P25: f32 = 3.0;
    pub const RAW_P50: f32 = 4.0;
    pub const RAW_P75: f32 = 8.0;
    pub const RAW_P90: f32 = 13.0;
    pub const RAW_P95: f32 = 16.0;
    pub const RAW_P99: f32 = 19.0;
    pub const TRANSFORMED_P01: f32 = 1.0;
    pub const TRANSFORMED_P05: f32 = 2.0;
    pub const TRANSFORMED_P10: f32 = 2.0;
    pub const TRANSFORMED_P25: f32 = 3.0;
    pub const TRANSFORMED_P50: f32 = 4.0;
    pub const TRANSFORMED_P75: f32 = 8.0;
    pub const TRANSFORMED_P90: f32 = 13.0;
    pub const TRANSFORMED_P95: f32 = 16.0;
    pub const TRANSFORMED_P99: f32 = 19.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.375;
    pub const NORMALIZED_P25: f32 = 1.0;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::TotalHeightPenalty {
    pub const RAW_P01: f32 = 4.0;
    pub const RAW_P05: f32 = 6.0;
    pub const RAW_P10: f32 = 8.0;
    pub const RAW_P25: f32 = 14.0;
    pub const RAW_P50: f32 = 29.0;
    pub const RAW_P75: f32 = 66.0;
    pub const RAW_P90: f32 = 102.0;
    pub const RAW_P95: f32 = 121.0;
    pub const RAW_P99: f32 = 143.0;
    pub const TRANSFORMED_P01: f32 = 4.0;
    pub const TRANSFORMED_P05: f32 = 6.0;
    pub const TRANSFORMED_P10: f32 = 8.0;
    pub const TRANSFORMED_P25: f32 = 14.0;
    pub const TRANSFORMED_P50: f32 = 29.0;
    pub const TRANSFORMED_P75: f32 = 66.0;
    pub const TRANSFORMED_P90: f32 = 102.0;
    pub const TRANSFORMED_P95: f32 = 121.0;
    pub const TRANSFORMED_P99: f32 = 143.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.165_217_4;
    pub const NORMALIZED_P25: f32 = 0.478_260_87;
    pub const NORMALIZED_P50: f32 = 0.8;
    pub const NORMALIZED_P75: f32 = 0.930_434_76;
    pub const NORMALIZED_P90: f32 = 0.982_608_7;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::LineClearBonus {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 0.0;
    pub const RAW_P75: f32 = 1.0;
    pub const RAW_P90: f32 = 1.0;
    pub const RAW_P95: f32 = 1.0;
    pub const RAW_P99: f32 = 2.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 0.0;
    pub const TRANSFORMED_P75: f32 = 0.0;
    pub const TRANSFORMED_P90: f32 = 0.0;
    pub const TRANSFORMED_P95: f32 = 0.0;
    pub const TRANSFORMED_P99: f32 = 1.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.0;
    pub const NORMALIZED_P25: f32 = 0.0;
    pub const NORMALIZED_P50: f32 = 0.0;
    pub const NORMALIZED_P75: f32 = 0.0;
    pub const NORMALIZED_P90: f32 = 0.0;
    pub const NORMALIZED_P95: f32 = 0.0;
    pub const NORMALIZED_P99: f32 = 0.166_666_67;
}

impl crate::board_feature::IWellReward {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 1.0;
    pub const RAW_P75: f32 = 3.0;
    pub const RAW_P90: f32 = 6.0;
    pub const RAW_P95: f32 = 9.0;
    pub const RAW_P99: f32 = 13.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 0.0;
    pub const TRANSFORMED_P75: f32 = 0.0;
    pub const TRANSFORMED_P90: f32 = 0.5;
    pub const TRANSFORMED_P95: f32 = 1.0;
    pub const TRANSFORMED_P99: f32 = 1.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.0;
    pub const NORMALIZED_P25: f32 = 0.0;
    pub const NORMALIZED_P50: f32 = 0.0;
    pub const NORMALIZED_P75: f32 = 0.0;
    pub const NORMALIZED_P90: f32 = 0.5;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}
