// This file is @generated by oxidris-cli generate-board-feature-stats.
// To regenerate, run: make regenerate-board-feature-stats

impl crate::board_feature::HolesPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 1.0;
    pub const RAW_P75: f32 = 4.0;
    pub const RAW_P90: f32 = 12.0;
    pub const RAW_P95: f32 = 17.0;
    pub const RAW_P99: f32 = 24.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 1.0;
    pub const TRANSFORMED_P75: f32 = 4.0;
    pub const TRANSFORMED_P90: f32 = 12.0;
    pub const TRANSFORMED_P95: f32 = 17.0;
    pub const TRANSFORMED_P99: f32 = 24.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.294_117_63;
    pub const NORMALIZED_P25: f32 = 0.764_705_9;
    pub const NORMALIZED_P50: f32 = 0.941_176_5;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::HoleDepthPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 2.0;
    pub const RAW_P75: f32 = 19.0;
    pub const RAW_P90: f32 = 73.0;
    pub const RAW_P95: f32 = 116.0;
    pub const RAW_P99: f32 = 196.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 2.0;
    pub const TRANSFORMED_P75: f32 = 19.0;
    pub const TRANSFORMED_P90: f32 = 73.0;
    pub const TRANSFORMED_P95: f32 = 116.0;
    pub const TRANSFORMED_P99: f32 = 196.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.370_689_63;
    pub const NORMALIZED_P25: f32 = 0.836_206_9;
    pub const NORMALIZED_P50: f32 = 0.982_758_64;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::RowTransitionsPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 3.0;
    pub const RAW_P10: f32 = 4.0;
    pub const RAW_P25: f32 = 6.0;
    pub const RAW_P50: f32 = 9.0;
    pub const RAW_P75: f32 = 20.0;
    pub const RAW_P90: f32 = 31.0;
    pub const RAW_P95: f32 = 36.0;
    pub const RAW_P99: f32 = 47.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 3.0;
    pub const TRANSFORMED_P10: f32 = 4.0;
    pub const TRANSFORMED_P25: f32 = 6.0;
    pub const TRANSFORMED_P50: f32 = 9.0;
    pub const TRANSFORMED_P75: f32 = 20.0;
    pub const TRANSFORMED_P90: f32 = 31.0;
    pub const TRANSFORMED_P95: f32 = 36.0;
    pub const TRANSFORMED_P99: f32 = 47.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.151_515_13;
    pub const NORMALIZED_P25: f32 = 0.484_848_5;
    pub const NORMALIZED_P50: f32 = 0.818_181_8;
    pub const NORMALIZED_P75: f32 = 0.909_090_9;
    pub const NORMALIZED_P90: f32 = 0.969_697;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::ColumnTransitionsPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 3.0;
    pub const RAW_P10: f32 = 4.0;
    pub const RAW_P25: f32 = 9.0;
    pub const RAW_P50: f32 = 11.0;
    pub const RAW_P75: f32 = 17.0;
    pub const RAW_P90: f32 = 25.0;
    pub const RAW_P95: f32 = 32.0;
    pub const RAW_P99: f32 = 42.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 3.0;
    pub const TRANSFORMED_P10: f32 = 4.0;
    pub const TRANSFORMED_P25: f32 = 9.0;
    pub const TRANSFORMED_P50: f32 = 11.0;
    pub const TRANSFORMED_P75: f32 = 17.0;
    pub const TRANSFORMED_P90: f32 = 25.0;
    pub const TRANSFORMED_P95: f32 = 32.0;
    pub const TRANSFORMED_P99: f32 = 42.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.241_379_32;
    pub const NORMALIZED_P25: f32 = 0.517_241_36;
    pub const NORMALIZED_P50: f32 = 0.724_137_9;
    pub const NORMALIZED_P75: f32 = 0.793_103_46;
    pub const NORMALIZED_P90: f32 = 0.965_517_2;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::SurfaceBumpinessPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 3.0;
    pub const RAW_P10: f32 = 3.0;
    pub const RAW_P25: f32 = 5.0;
    pub const RAW_P50: f32 = 7.0;
    pub const RAW_P75: f32 = 12.0;
    pub const RAW_P90: f32 = 18.0;
    pub const RAW_P95: f32 = 25.0;
    pub const RAW_P99: f32 = 41.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 3.0;
    pub const TRANSFORMED_P10: f32 = 3.0;
    pub const TRANSFORMED_P25: f32 = 5.0;
    pub const TRANSFORMED_P50: f32 = 7.0;
    pub const TRANSFORMED_P75: f32 = 12.0;
    pub const TRANSFORMED_P90: f32 = 18.0;
    pub const TRANSFORMED_P95: f32 = 25.0;
    pub const TRANSFORMED_P99: f32 = 41.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.318_181_8;
    pub const NORMALIZED_P25: f32 = 0.590_909_1;
    pub const NORMALIZED_P50: f32 = 0.818_181_8;
    pub const NORMALIZED_P75: f32 = 0.909_090_9;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::SurfaceRoughnessPenalty {
    pub const RAW_P01: f32 = 2.0;
    pub const RAW_P05: f32 = 4.0;
    pub const RAW_P10: f32 = 5.0;
    pub const RAW_P25: f32 = 6.0;
    pub const RAW_P50: f32 = 9.0;
    pub const RAW_P75: f32 = 13.0;
    pub const RAW_P90: f32 = 20.0;
    pub const RAW_P95: f32 = 30.0;
    pub const RAW_P99: f32 = 58.0;
    pub const TRANSFORMED_P01: f32 = 2.0;
    pub const TRANSFORMED_P05: f32 = 4.0;
    pub const TRANSFORMED_P10: f32 = 5.0;
    pub const TRANSFORMED_P25: f32 = 6.0;
    pub const TRANSFORMED_P50: f32 = 9.0;
    pub const TRANSFORMED_P75: f32 = 13.0;
    pub const TRANSFORMED_P90: f32 = 20.0;
    pub const TRANSFORMED_P95: f32 = 30.0;
    pub const TRANSFORMED_P99: f32 = 58.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.384_615_36;
    pub const NORMALIZED_P25: f32 = 0.653_846_14;
    pub const NORMALIZED_P50: f32 = 0.807_692_3;
    pub const NORMALIZED_P75: f32 = 0.923_076_9;
    pub const NORMALIZED_P90: f32 = 0.961_538_43;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::WellDepthPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 1.0;
    pub const RAW_P75: f32 = 3.0;
    pub const RAW_P90: f32 = 6.0;
    pub const RAW_P95: f32 = 12.0;
    pub const RAW_P99: f32 = 21.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 1.0;
    pub const TRANSFORMED_P75: f32 = 3.0;
    pub const TRANSFORMED_P90: f32 = 6.0;
    pub const TRANSFORMED_P95: f32 = 12.0;
    pub const TRANSFORMED_P99: f32 = 21.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.5;
    pub const NORMALIZED_P25: f32 = 0.75;
    pub const NORMALIZED_P50: f32 = 0.916_666_7;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::DeepWellRisk {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 1.0;
    pub const RAW_P75: f32 = 3.0;
    pub const RAW_P90: f32 = 6.0;
    pub const RAW_P95: f32 = 12.0;
    pub const RAW_P99: f32 = 21.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 1.0;
    pub const TRANSFORMED_P75: f32 = 3.0;
    pub const TRANSFORMED_P90: f32 = 6.0;
    pub const TRANSFORMED_P95: f32 = 12.0;
    pub const TRANSFORMED_P99: f32 = 21.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.666_666_6;
    pub const NORMALIZED_P25: f32 = 1.0;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::MaxHeightPenalty {
    pub const RAW_P01: f32 = 1.0;
    pub const RAW_P05: f32 = 1.0;
    pub const RAW_P10: f32 = 2.0;
    pub const RAW_P25: f32 = 2.0;
    pub const RAW_P50: f32 = 4.0;
    pub const RAW_P75: f32 = 9.0;
    pub const RAW_P90: f32 = 14.0;
    pub const RAW_P95: f32 = 16.0;
    pub const RAW_P99: f32 = 17.0;
    pub const TRANSFORMED_P01: f32 = 1.0;
    pub const TRANSFORMED_P05: f32 = 1.0;
    pub const TRANSFORMED_P10: f32 = 2.0;
    pub const TRANSFORMED_P25: f32 = 2.0;
    pub const TRANSFORMED_P50: f32 = 4.0;
    pub const TRANSFORMED_P75: f32 = 9.0;
    pub const TRANSFORMED_P90: f32 = 14.0;
    pub const TRANSFORMED_P95: f32 = 16.0;
    pub const TRANSFORMED_P99: f32 = 17.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.133_333_33;
    pub const NORMALIZED_P25: f32 = 0.466_666_64;
    pub const NORMALIZED_P50: f32 = 0.8;
    pub const NORMALIZED_P75: f32 = 0.933_333_34;
    pub const NORMALIZED_P90: f32 = 0.933_333_34;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::CenterColumnsPenalty {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 1.0;
    pub const RAW_P25: f32 = 2.0;
    pub const RAW_P50: f32 = 3.0;
    pub const RAW_P75: f32 = 8.0;
    pub const RAW_P90: f32 = 13.0;
    pub const RAW_P95: f32 = 15.0;
    pub const RAW_P99: f32 = 17.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 1.0;
    pub const TRANSFORMED_P25: f32 = 2.0;
    pub const TRANSFORMED_P50: f32 = 3.0;
    pub const TRANSFORMED_P75: f32 = 8.0;
    pub const TRANSFORMED_P90: f32 = 13.0;
    pub const TRANSFORMED_P95: f32 = 15.0;
    pub const TRANSFORMED_P99: f32 = 17.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.133_333_33;
    pub const NORMALIZED_P25: f32 = 0.466_666_64;
    pub const NORMALIZED_P50: f32 = 0.8;
    pub const NORMALIZED_P75: f32 = 0.866_666_7;
    pub const NORMALIZED_P90: f32 = 0.933_333_34;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::CenterTopOutRisk {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 1.0;
    pub const RAW_P25: f32 = 2.0;
    pub const RAW_P50: f32 = 3.0;
    pub const RAW_P75: f32 = 8.0;
    pub const RAW_P90: f32 = 13.0;
    pub const RAW_P95: f32 = 15.0;
    pub const RAW_P99: f32 = 17.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 1.0;
    pub const TRANSFORMED_P25: f32 = 2.0;
    pub const TRANSFORMED_P50: f32 = 3.0;
    pub const TRANSFORMED_P75: f32 = 8.0;
    pub const TRANSFORMED_P90: f32 = 13.0;
    pub const TRANSFORMED_P95: f32 = 15.0;
    pub const TRANSFORMED_P99: f32 = 17.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.285_714_27;
    pub const NORMALIZED_P25: f32 = 1.0;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::TopOutRisk {
    pub const RAW_P01: f32 = 1.0;
    pub const RAW_P05: f32 = 1.0;
    pub const RAW_P10: f32 = 2.0;
    pub const RAW_P25: f32 = 2.0;
    pub const RAW_P50: f32 = 4.0;
    pub const RAW_P75: f32 = 9.0;
    pub const RAW_P90: f32 = 14.0;
    pub const RAW_P95: f32 = 16.0;
    pub const RAW_P99: f32 = 17.0;
    pub const TRANSFORMED_P01: f32 = 1.0;
    pub const TRANSFORMED_P05: f32 = 1.0;
    pub const TRANSFORMED_P10: f32 = 2.0;
    pub const TRANSFORMED_P25: f32 = 2.0;
    pub const TRANSFORMED_P50: f32 = 4.0;
    pub const TRANSFORMED_P75: f32 = 9.0;
    pub const TRANSFORMED_P90: f32 = 14.0;
    pub const TRANSFORMED_P95: f32 = 16.0;
    pub const TRANSFORMED_P99: f32 = 17.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.285_714_27;
    pub const NORMALIZED_P25: f32 = 1.0;
    pub const NORMALIZED_P50: f32 = 1.0;
    pub const NORMALIZED_P75: f32 = 1.0;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::TotalHeightPenalty {
    pub const RAW_P01: f32 = 4.0;
    pub const RAW_P05: f32 = 4.0;
    pub const RAW_P10: f32 = 4.0;
    pub const RAW_P25: f32 = 14.0;
    pub const RAW_P50: f32 = 25.0;
    pub const RAW_P75: f32 = 68.0;
    pub const RAW_P90: f32 = 103.0;
    pub const RAW_P95: f32 = 118.0;
    pub const RAW_P99: f32 = 132.0;
    pub const TRANSFORMED_P01: f32 = 4.0;
    pub const TRANSFORMED_P05: f32 = 4.0;
    pub const TRANSFORMED_P10: f32 = 4.0;
    pub const TRANSFORMED_P25: f32 = 14.0;
    pub const TRANSFORMED_P50: f32 = 25.0;
    pub const TRANSFORMED_P75: f32 = 68.0;
    pub const TRANSFORMED_P90: f32 = 103.0;
    pub const TRANSFORMED_P95: f32 = 118.0;
    pub const TRANSFORMED_P99: f32 = 132.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.131_578_92;
    pub const NORMALIZED_P25: f32 = 0.438_596_5;
    pub const NORMALIZED_P50: f32 = 0.815_789_46;
    pub const NORMALIZED_P75: f32 = 0.912_280_7;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}

impl crate::board_feature::LineClearBonus {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 0.0;
    pub const RAW_P50: f32 = 0.0;
    pub const RAW_P75: f32 = 0.0;
    pub const RAW_P90: f32 = 1.0;
    pub const RAW_P95: f32 = 1.0;
    pub const RAW_P99: f32 = 2.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 0.0;
    pub const TRANSFORMED_P75: f32 = 0.0;
    pub const TRANSFORMED_P90: f32 = 0.0;
    pub const TRANSFORMED_P95: f32 = 0.0;
    pub const TRANSFORMED_P99: f32 = 1.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.0;
    pub const NORMALIZED_P25: f32 = 0.0;
    pub const NORMALIZED_P50: f32 = 0.0;
    pub const NORMALIZED_P75: f32 = 0.0;
    pub const NORMALIZED_P90: f32 = 0.0;
    pub const NORMALIZED_P95: f32 = 0.0;
    pub const NORMALIZED_P99: f32 = 0.166_666_67;
}

impl crate::board_feature::IWellReward {
    pub const RAW_P01: f32 = 0.0;
    pub const RAW_P05: f32 = 0.0;
    pub const RAW_P10: f32 = 0.0;
    pub const RAW_P25: f32 = 1.0;
    pub const RAW_P50: f32 = 1.0;
    pub const RAW_P75: f32 = 4.0;
    pub const RAW_P90: f32 = 5.0;
    pub const RAW_P95: f32 = 8.0;
    pub const RAW_P99: f32 = 12.0;
    pub const TRANSFORMED_P01: f32 = 0.0;
    pub const TRANSFORMED_P05: f32 = 0.0;
    pub const TRANSFORMED_P10: f32 = 0.0;
    pub const TRANSFORMED_P25: f32 = 0.0;
    pub const TRANSFORMED_P50: f32 = 0.0;
    pub const TRANSFORMED_P75: f32 = 0.5;
    pub const TRANSFORMED_P90: f32 = 1.0;
    pub const TRANSFORMED_P95: f32 = 1.0;
    pub const TRANSFORMED_P99: f32 = 1.0;
    pub const NORMALIZED_P01: f32 = 0.0;
    pub const NORMALIZED_P05: f32 = 0.0;
    pub const NORMALIZED_P10: f32 = 0.0;
    pub const NORMALIZED_P25: f32 = 0.0;
    pub const NORMALIZED_P50: f32 = 0.0;
    pub const NORMALIZED_P75: f32 = 0.5;
    pub const NORMALIZED_P90: f32 = 1.0;
    pub const NORMALIZED_P95: f32 = 1.0;
    pub const NORMALIZED_P99: f32 = 1.0;
}
