//! Interactive board feature analysis command
//!
//! This module provides the `analyze-board-features` subcommand, which loads
//! board session data, computes features with normalization, and launches an
//! interactive TUI for exploring feature distributions and statistics.
//!
//! # Usage
//!
//! ```bash
//! oxidris-cli analyze-board-features data/boards.json
//! ```
//!
//! # Features
//!
//! - Load board session data from JSON
//! - Build all features (raw + table transforms) with normalization
//! - Compute feature statistics (percentiles, distributions)
//! - Build board index for efficient feature-based queries
//! - Launch interactive TUI for exploration
//!
//! # See Also
//!
//! - [`BoardSample`] - Feature value extraction from boards
//! - [`BoardFeatureStatistics`] - Statistical analysis of features
//! - [`BoardIndex`] - Efficient feature-based board lookup

use std::path::PathBuf;

use oxidris_analysis::{
    index::BoardIndex, sample::BoardSample, statistics::BoardFeatureStatistics,
};

use crate::{
    command::analyze_board_features::app::AnalyzeBoardApp,
    tui::Tui,
    util::{self, FeatureSet},
};

mod app;
mod screens;

/// Command-line arguments for analyze-board-features subcommand
#[derive(Default, Debug, Clone, clap::Args)]
pub(crate) struct AnalyzeBoardFeaturesArg {
    /// Board data file path (JSON format)
    ///
    /// This file should contain session data generated by the
    /// `generate-boards` command.
    boards_file: PathBuf,
}

/// Run the analyze-board-features command
///
/// This function performs the following steps:
///
/// 1. Load board session data from JSON file
/// 2. Build all features (raw + table) with computed normalization
/// 3. Compute feature values for all boards in all sessions
/// 4. Calculate feature statistics (percentiles, distributions)
/// 5. Build board index for efficient feature-based queries
/// 6. Launch interactive TUI for feature exploration
///
/// # Arguments
///
/// * `arg` - Command-line arguments (boards file path)
///
/// # Returns
///
/// Success if TUI completes normally, error otherwise
///
/// # Errors
///
/// Returns error if:
/// - Boards file cannot be read or parsed
/// - Feature building fails (missing normalization data)
/// - Statistics computation fails
/// - TUI fails to launch or encounters runtime error
pub fn run(arg: &AnalyzeBoardFeaturesArg) -> anyhow::Result<()> {
    let AnalyzeBoardFeaturesArg { boards_file } = arg;

    eprintln!("Loading boards from {}...", boards_file.display());
    let sessions = util::read_boards_file(boards_file)?.sessions;
    eprintln!("Loaded {} sessions", sessions.len());

    let features = util::build_feature_from_session(FeatureSet::All, &sessions)?;

    eprintln!("Computing features for all boards...");
    let board_samples = BoardSample::from_sessions(&features, &sessions);
    eprintln!("Features computed");

    eprintln!("Computing statistics");
    let statistics = BoardFeatureStatistics::from_samples(&features, &board_samples);
    eprintln!("Statistics computed");

    eprintln!("Building board index...");
    let board_index = BoardIndex::from_samples(&features, &board_samples);
    eprintln!("Board index built");

    let mut app = AnalyzeBoardApp::new(features, board_samples, statistics, board_index);
    Tui::new().run(&mut app)?;

    Ok(())
}
