use std::{
    io::{self, Write as _},
    iter,
    path::PathBuf,
};

use anyhow::Context as _;
use oxidris_evaluator::board_feature::{self, BoxedBoardFeature};

use crate::{
    analysis,
    data::{self, BoardFeatureStatistics},
    util::{self, Output},
};

#[derive(Default, Debug, Clone, clap::Args)]
pub(crate) struct GenerateBoardFeatureStatsArg {
    /// Boards data file path
    boards_file: PathBuf,
    /// Output file path
    #[arg(long)]
    output: Option<PathBuf>,
}

pub fn run(arg: &GenerateBoardFeatureStatsArg) -> anyhow::Result<()> {
    let GenerateBoardFeatureStatsArg {
        boards_file,
        output,
    } = arg;

    let features = board_feature::all_board_features();

    eprintln!("Loading boards from {}...", boards_file.display());
    let boards = data::load_session_collection(boards_file)?.sessions;
    eprintln!("Loaded {} boards", boards.len());

    eprintln!("Computing featuress for all boards...");
    let board_samples = analysis::extract_all_board_features(&features, &boards);
    eprintln!("Features computed");

    eprintln!("Computing statistics");
    let statistics = analysis::coimpute_statistics(&features, &board_samples);
    eprintln!("Statistics computed");

    let mut writer = Output::from_output_path(output.clone())?;
    dump_source(&mut writer, &features, &statistics).with_context(|| {
        format!(
            "Failed to write source code to {}",
            output
                .as_ref()
                .map_or_else(|| "stdout".to_string(), |p| p.display().to_string())
        )
    })?;
    writer.flush().with_context(|| {
        format!(
            "Failed to write source code to {}",
            output
                .as_ref()
                .map_or_else(|| "stdout".to_string(), |p| p.display().to_string())
        )
    })?;

    Ok(())
}

fn dump_source(
    writer: &mut dyn io::Write,
    features: &[BoxedBoardFeature],
    statistics: &[BoardFeatureStatistics],
) -> anyhow::Result<()> {
    writeln!(
        writer,
        "// This file is @generated by oxidris-cli generate-board-feature-stats."
    )?;
    writeln!(
        writer,
        "// To regenerate, run: make regenerate-board-feature-stats"
    )?;
    for (f, stats) in iter::zip(features, statistics) {
        writeln!(writer)?;
        writeln!(
            writer,
            "impl {} {{",
            f.type_name().replace("oxidris_ai::", "crate::")
        )?;
        for (kind, stats) in [
            ("RAW", &stats.raw),
            ("TRANSFORMED", &stats.transformed),
            ("NORMALIZED", &stats.normalized),
        ] {
            for percentile in [1u8, 5, 10, 25, 50, 75, 90, 95, 99] {
                let value = stats.percentiles.get(f32::from(percentile)).unwrap();
                let s = util::format_f32(value);
                writeln!(writer, "    pub const {kind}_P{percentile:02}: f32 = {s};",)?;
            }
        }
        writeln!(writer, "}}")?;
    }

    Ok(())
}
